
import { type Conversation } from "../types/index";

export const conversationList : Conversation[] = [
  {
    id: 1,
    username: "John Doe",
    avatar: "/avatars/john.jpg",
    lastMessage: "Hey, how are you doing?",
    allMessages: [
      {
        id: 1,
        sender: "John Doe",
        receiver: "You",
        text: "Hey, how are you doing?",
        timestamp: "2026-09-15T10:25:00Z",
      },
      {
        id: 2,
        sender: "You",
        receiver: "John Doe",
        text: "I'm doing great! How about you?",
        timestamp: "2026-09-15T10:26:00Z",
      },
      {
        id: 3,
        sender: "John Doe",
        receiver: "You",
        text: "I'm good too. Are you working on the project?",
        timestamp: "2026-09-15T10:28:00Z",
      },
      {
        id: 4,
        sender: "You",
        receiver: "John Doe",
        text: "Yes, I'm working on it right now.",
        timestamp: "2026-09-15T10:29:00Z",
      },
      {
        id: 5,
        sender: "John Doe",
        receiver: "You",
        text: "Hey, how are you doing?",
        timestamp: "2026-09-15T10:30:00Z",
      },
    ],
    timestamp: "2026-09-15T10:30:00Z",
    unreadCount: 2,
    isOnline: true,
  },

  {
    id: 2,
    username: "Jane Smith",
    avatar: "/avatars/jane.jpg",
    lastMessage: "See you tomorrow!",
    allMessages: [
      {
        id: 1,
        sender: "You",
        receiver: "Jane Smith",
        text: "Are we still meeting tomorrow?",
        timestamp: "2026-09-15T09:05:00Z",
      },
      {
        id: 2,
        sender: "Jane Smith",
        receiver: "You",
        text: "Yes, definitely.",
        timestamp: "2026-09-15T09:08:00Z",
      },
      {
        id: 3,
        sender: "You",
        receiver: "Jane Smith",
        text: "What time should I come?",
        timestamp: "2026-09-15T09:10:00Z",
      },
      {
        id: 4,
        sender: "Jane Smith",
        receiver: "You",
        text: "Around 10 AM.",
        timestamp: "2026-09-15T09:12:00Z",
      },
      {
        id: 5,
        sender: "Jane Smith",
        receiver: "You",
        text: "See you tomorrow!",
        timestamp: "2026-09-15T09:15:00Z",
      },
    ],
    timestamp: "2026-09-15T09:15:00Z",
    unreadCount: 0,
    isOnline: false,
  },

  {
    id: 3,
    username: "Bob Johnson",
    avatar: "/avatars/bob.jpg",
    lastMessage: "Thanks for your help!",
    allMessages: [
      {
        id: 1,
        sender: "Bob Johnson",
        receiver: "You",
        text: "Can you help me with the API?",
        timestamp: "2026-09-14T18:30:00Z",
      },
      {
        id: 2,
        sender: "You",
        receiver: "Bob Johnson",
        text: "Sure. What problem are you facing?",
        timestamp: "2026-09-14T18:32:00Z",
      },
      {
        id: 3,
        sender: "Bob Johnson",
        receiver: "You",
        text: "I'm getting an error from the server.",
        timestamp: "2026-09-14T18:35:00Z",
      },
      {
        id: 4,
        sender: "You",
        receiver: "Bob Johnson",
        text: "Check the request body and authorization token.",
        timestamp: "2026-09-14T18:40:00Z",
      },
      {
        id: 5,
        sender: "Bob Johnson",
        receiver: "You",
        text: "Thanks for your help!",
        timestamp: "2026-09-14T18:45:00Z",
      },
    ],
    timestamp: "2026-09-14T18:45:00Z",
    unreadCount: 5,
    isOnline: true,
  },

  {
    id: 4,
    username: "Sarah Williams",
    avatar: "/avatars/sarah.jpg",
    lastMessage: "I'll send you the documents tonight.",
    allMessages: [
      {
        id: 1,
        sender: "You",
        receiver: "Sarah Williams",
        text: "Did you finish the documents?",
        timestamp: "2026-09-14T16:00:00Z",
      },
      {
        id: 2,
        sender: "Sarah Williams",
        receiver: "You",
        text: "Almost finished.",
        timestamp: "2026-09-14T16:05:00Z",
      },
      {
        id: 3,
        sender: "You",
        receiver: "Sarah Williams",
        text: "Great. Please send them when you're done.",
        timestamp: "2026-09-14T16:10:00Z",
      },
      {
        id: 4,
        sender: "Sarah Williams",
        receiver: "You",
        text: "I'll send you the documents tonight.",
        timestamp: "2026-09-14T16:20:00Z",
      },
    ],
    timestamp: "2026-09-14T16:20:00Z",
    unreadCount: 1,
    isOnline: true,
  },

  {
    id: 5,
    username: "Michael Brown",
    avatar: "/avatars/michael.jpg",
    lastMessage: "Let's discuss this tomorrow.",
    allMessages: [
      {
        id: 1,
        sender: "Michael Brown",
        receiver: "You",
        text: "I have an idea for the new feature.",
        timestamp: "2026-09-14T13:50:00Z",
      },
      {
        id: 2,
        sender: "You",
        receiver: "Michael Brown",
        text: "Sounds interesting. Tell me more.",
        timestamp: "2026-09-14T13:55:00Z",
      },
      {
        id: 3,
        sender: "Michael Brown",
        receiver: "You",
        text: "I think we can improve the dashboard.",
        timestamp: "2026-09-14T14:00:00Z",
      },
      {
        id: 4,
        sender: "You",
        receiver: "Michael Brown",
        text: "Let's review it together.",
        timestamp: "2026-09-14T14:05:00Z",
      },
      {
        id: 5,
        sender: "Michael Brown",
        receiver: "You",
        text: "Let's discuss this tomorrow.",
        timestamp: "2026-09-14T14:10:00Z",
      },
    ],
    timestamp: "2026-09-14T14:10:00Z",
    unreadCount: 0,
    isOnline: false,
  },

  {
    id: 6,
    username: "Emily Davis",
    avatar: "/avatars/emily.jpg",
    lastMessage: "That sounds great! 👍",
    allMessages: [
      {
        id: 1,
        sender: "You",
        receiver: "Emily Davis",
        text: "Are you available for a quick call?",
        timestamp: "2026-09-13T21:10:00Z",
      },
      {
        id: 2,
        sender: "Emily Davis",
        receiver: "You",
        text: "Yes, give me a few minutes.",
        timestamp: "2026-09-13T21:15:00Z",
      },
      {
        id: 3,
        sender: "You",
        receiver: "Emily Davis",
        text: "No problem.",
        timestamp: "2026-09-13T21:20:00Z",
      },
      {
        id: 4,
        sender: "Emily Davis",
        receiver: "You",
        text: "I just checked the design.",
        timestamp: "2026-09-13T21:25:00Z",
      },
      {
        id: 5,
        sender: "You",
        receiver: "Emily Davis",
        text: "What do you think?",
        timestamp: "2026-09-13T21:28:00Z",
      },
      {
        id: 6,
        sender: "Emily Davis",
        receiver: "You",
        text: "That sounds great! 👍",
        timestamp: "2026-09-13T21:30:00Z",
      },
    ],
    timestamp: "2026-09-13T21:30:00Z",
    unreadCount: 3,
    isOnline: true,
  },

  {
    id: 7,
    username: "David Wilson",
    avatar: "/avatars/david.jpg",
    lastMessage: "Can you check the latest update?",
    allMessages: [
      {
        id: 1,
        sender: "David Wilson",
        receiver: "You",
        text: "The deployment is almost ready.",
        timestamp: "2026-09-13T18:40:00Z",
      },
      {
        id: 2,
        sender: "You",
        receiver: "David Wilson",
        text: "Did you test the production build?",
        timestamp: "2026-09-13T18:45:00Z",
      },
      {
        id: 3,
        sender: "David Wilson",
        receiver: "You",
        text: "Yes, everything looks good.",
        timestamp: "2026-09-13T18:55:00Z",
      },
      {
        id: 4,
        sender: "David Wilson",
        receiver: "You",
        text: "Can you check the latest update?",
        timestamp: "2026-09-13T19:05:00Z",
      },
    ],
    timestamp: "2026-09-13T19:05:00Z",
    unreadCount: 0,
    isOnline: false,
  },
];
